version: '{build}'
environment:
  nodejs_version: 0.12
install:
- ps: Install-Product node $env:nodejs_version
- npm install
- npm install -g gulp grunt-cli
build_script:
- gulp
- gulp package
- grunt create-windows-installer
test: off
artifacts:
- path: builds\windows\*.exe
  name: Setup
deploy:
- provider: S3
  access_key_id: AKIAJH2DBYS7C32UWIJA
  secret_access_key:
    secure: DC7kd3kX/qWb2iQo8q1Wbae6/irThC7uS6J+2Bm1TejFRtNVSqBXtY3QYKsCFLw5
  bucket: musicpicker-releases
  set_public: true
  folder: /latest/win64
  artifact: Setup
  on:
    branch: master
